## Server configuration
server:
  port: 8080
# Spring Boot configuration
spring:
  # Database
  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bartender
    username: root
    password:
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #    database: postgresql
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
# Logger configuration
logging:
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  level:
    org.springframework: INFO
    org.hibernate: DEBUG


